// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Contents/ContentAccordeon.tsx";
import * as $$$$$$1 from "./sections/Contents/ContentComparisonTitle.tsx";
import * as $$$$$$2 from "./sections/Contents/ContentIconGroup.tsx";
import * as $$$$$$3 from "./sections/Contents/ContentImage.tsx";
import * as $$$$$$4 from "./sections/Contents/ContentProduct.tsx";
import * as $$$$$$5 from "./sections/Contents/ContentText.tsx";
import * as $$$$$$6 from "./sections/Destaques/Duvidas.tsx";
import * as $$$$$$7 from "./sections/Destaques/FixedSection.tsx";
import * as $$$$$$8 from "./sections/Destaques/GrandesNumeros.tsx";
import * as $$$$$$9 from "./sections/Destaques/IdealPlan.tsx";
import * as $$$$$$10 from "./sections/Destaques/ListImage.tsx";
import * as $$$$$$11 from "./sections/Destaques/ListText.tsx";
import * as $$$$$$12 from "./sections/Destaques/Parcerias.tsx";
import * as $$$$$$13 from "./sections/Destaques/Tutorial.tsx";
import * as $$$$$$14 from "./sections/Footer.tsx";
import * as $$$$$$15 from "./sections/Galery/GaleryContent.tsx";
import * as $$$$$$16 from "./sections/Galery/GaleryWithLink.tsx";
import * as $$$$$$17 from "./sections/Galery/ImageContent.tsx";
import * as $$$$$$18 from "./sections/Headers/Offer.tsx";
import * as $$$$$$19 from "./sections/Headers/Openning.tsx";
import * as $$$$$$20 from "./sections/Headers/SubtitleWithShareIcon.tsx";
import * as $$$$$$21 from "./sections/Headers/TitleArticle.tsx";
import * as $$$$$$22 from "./sections/Headers/TitleError.tsx";
import * as $$$$$$23 from "./sections/Headers/TitleIntegration.tsx";
import * as $$$$$$24 from "./sections/Headers/TitleLarge.tsx";
import * as $$$$$$25 from "./sections/Headers/TitleMedium.tsx";
import * as $$$$$$26 from "./sections/Headers/TitleMonteSeuPlano.tsx";
import * as $$$$$$27 from "./sections/Headers/TitlePlan.tsx";
import * as $$$$$$28 from "./sections/Headers/TitleSegment.tsx";
import * as $$$$$$29 from "./sections/Headers/TitleSuccess.tsx";
import * as $$$$$$30 from "./sections/ItWorks.tsx";
import * as $$$$$$31 from "./sections/Navigation/Categorias.tsx";
import * as $$$$$$32 from "./sections/Navigation/Navbar.tsx";
import * as $$$$$$33 from "./sections/Navigation/Tabs.tsx";
import * as $$$$$$34 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/Contents/ContentAccordeon.tsx": $$$$$$0,
    "site/sections/Contents/ContentComparisonTitle.tsx": $$$$$$1,
    "site/sections/Contents/ContentIconGroup.tsx": $$$$$$2,
    "site/sections/Contents/ContentImage.tsx": $$$$$$3,
    "site/sections/Contents/ContentProduct.tsx": $$$$$$4,
    "site/sections/Contents/ContentText.tsx": $$$$$$5,
    "site/sections/Destaques/Duvidas.tsx": $$$$$$6,
    "site/sections/Destaques/FixedSection.tsx": $$$$$$7,
    "site/sections/Destaques/GrandesNumeros.tsx": $$$$$$8,
    "site/sections/Destaques/IdealPlan.tsx": $$$$$$9,
    "site/sections/Destaques/ListImage.tsx": $$$$$$10,
    "site/sections/Destaques/ListText.tsx": $$$$$$11,
    "site/sections/Destaques/Parcerias.tsx": $$$$$$12,
    "site/sections/Destaques/Tutorial.tsx": $$$$$$13,
    "site/sections/Footer.tsx": $$$$$$14,
    "site/sections/Galery/GaleryContent.tsx": $$$$$$15,
    "site/sections/Galery/GaleryWithLink.tsx": $$$$$$16,
    "site/sections/Galery/ImageContent.tsx": $$$$$$17,
    "site/sections/Headers/Offer.tsx": $$$$$$18,
    "site/sections/Headers/Openning.tsx": $$$$$$19,
    "site/sections/Headers/SubtitleWithShareIcon.tsx": $$$$$$20,
    "site/sections/Headers/TitleArticle.tsx": $$$$$$21,
    "site/sections/Headers/TitleError.tsx": $$$$$$22,
    "site/sections/Headers/TitleIntegration.tsx": $$$$$$23,
    "site/sections/Headers/TitleLarge.tsx": $$$$$$24,
    "site/sections/Headers/TitleMedium.tsx": $$$$$$25,
    "site/sections/Headers/TitleMonteSeuPlano.tsx": $$$$$$26,
    "site/sections/Headers/TitlePlan.tsx": $$$$$$27,
    "site/sections/Headers/TitleSegment.tsx": $$$$$$28,
    "site/sections/Headers/TitleSuccess.tsx": $$$$$$29,
    "site/sections/ItWorks.tsx": $$$$$$30,
    "site/sections/Navigation/Categorias.tsx": $$$$$$31,
    "site/sections/Navigation/Navbar.tsx": $$$$$$32,
    "site/sections/Navigation/Tabs.tsx": $$$$$$33,
    "site/sections/Theme/Theme.tsx": $$$$$$34,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
